spring.application.name=class3
server.port=8082

aws.dynamo.table-name=academia-java-aws
aws.dynamo.partition-key=aula-6

aws.sns.region=us-east-2
aws.sns.topic-arn=arn:aws:sns:us-east-2:606103596924:academia-aws-aula-8
aws.sns.display-name=ana-aula/8

aws.sqs.region=us-east-2
aws.sqs.queue-name=aula-7
aws.sqs.queue-arn=arn:aws:sqs:us-east-2:606103596924:aula-7
aws.sqs.queue-url=https://sqs.us-east-2.amazonaws.com/606103596924/aula-7
